[BUG][STACK-1510]: When ohm is enabled, child project resources gets created in parent partition of vthunder
a10networks/a10-octavia pull request #170
Opened 2020-09-02 14:54 UTC by afrin-chakure-a10

## Description
**STACK-1510**
- Severity Level: **High**
- If `use_parent_partition` is True, listener cannot be created under the previous loadbalancer if modify the `project_id` in `a10-octavia.conf`
- In other words, `Child2` project's listener was not getting created in parent partition when `use_parent_partition` is True, and LB is created from `Child1` project.

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-1510

## Technical Approach
_(The setup tested for : there is an `admin` project and `child1` and `child2` project are its children.)_
- It was found that the listener's `project_id` comes from the LB's `project_id` it is attached to and **not** on the sourced project.
- When use_parent_partition is enabled, keeping `hmt` - enabled, when listener intended from `child2` project is fired to get attached to LB of `child1` project, error occured.
- It was failing at the **_if_** condition at `controller_worker` level, and going over to _non-rack_ flow. Eventually it leads to `MissingSecurityGroup` Error.

- Hence, more conditions on above **if** statement were added to also match parent projects like: 
 (a) Fetch parent projects of all the projects mentioned in config. 
 (b) Check if `listener.project_id`  exist in above list (a). [in case listener create openstack cmd is fired from `child1` project attached to an LB belonging to `admin` project]
 (c) Check if parent project id of `listener.project_id`  in above list (a).[in case listener create openstack cmd is fired from `child2` project attached to an LB belonging to `child1` project]

- If while getting parent project_id, if given config `project_id` is invalid/doesn't exist, we return None.

## Config Changes
None

## Test Cases

- If `use_parent_partition` = True and `hierarchical_multitenancy` is `enable`:

Config project | Parent Resource | Resource | Vthunder partition
-- | -- | -- | --
admin | LB(admin) | Listener | admin
child1 | LB(admin) | Listener | admin
child2 | LB(admin) | Listener | admin
  |   |   |  
child1 | LB(child1) | Listener | admin
  |   |   |  
child2 | LB(child1) | Listener | admin
child2 | LB(child2) | Listener | admin
  |   |   |  
Invalid | LB(admin) | Listener | -- (Goes to non-RACK flow, throw error)
Invalid | LB(child1) | Listener | -- (Goes to non-RACK flow, throw error)
Invalid | LB(child2) | Listener | -- (Goes to non-RACK flow, throw error)

-  When `use_parent_partition` = False and `hierarchical_multitenancy` is `disable`:

Config project | Parent Resource | Resource | Vthunder partition
-- | -- | -- | --
admin | LB(admin) | Listener | admin
child1 | LB(admin) | Listener | -- (Goes to non-RACK flow, throw error)
child2 | LB(admin) | Listener | -- (Goes to non-RACK flow, throw error)
  |   |   |  
child1 | LB(child1) | Listener | child1
  |   |   |  
child2 | LB(child1) | Listener | -- (Goes to non-RACK flow, throw error)
child2 | LB(child2) | Listener | child2
  |   |   |  
Invalid | LB(admin) | Listener | -- (Goes to non-RACK flow, throw error)
Invalid | LB(child1) | Listener | -- (Goes to non-RACK flow, throw error)
Invalid | LB(child2) | Listener | -- (Goes to non-RACK flow, throw error)

** similar test cases are applicable for pool and member.

## Manual Testing
- One scenario is same as mentioned in Steps to reproduce of [STACK-1510](https://a10networks.atlassian.net/browse/STACK-1510)

2020-09-08 17:20 UTC, OmkarTelee-A10 submitted a review, later dismissed

2020-09-08 23:33 UTC, hthompson-a10 requested changes

2020-09-08 23:33 UTC, hthompson-a10 commented on a10_octavia/controller/worker/controller_worker.py
> +        if any([any([proj in utils.get_parent_project_list() for proj in (listener.project_id,
This is some pretty messy list comprehension. Splitting it up a bit would make the section far more readable for a similar performance and LOC cost.

2020-09-15 06:00 UTC, afrin-chakure-a10 commented
@hthompson-a10 
Removed list comprehension usage and expanded if-conditions for better readabilty.

2020-09-17 07:22 UTC, hthompson-a10 approved these changes

2020-09-17 09:52 UTC, OmkarTelee-A10 approved these changes

2020-09-17 09:52 UTC, merged