STACK-1612: Handled case for None description while creating lb
a10networks/a10-octavia pull request #191
Opened 2020-09-23 09:10 UTC by NehaKembalkarA10

## Description
Resolved the issue facing while creating a loadbalancer without giving description

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-1612

## Technical Approach
- Trimming the description only when provided description is " "

## Related PR
https://github.com/a10networks/acos-client/pull/294

## Manual Testing
Following are the results for the steps mentioned in the bug by referring lb1 as lb2 and lb2 as lb3 here

1. 
![image](https://user-images.githubusercontent.com/58077446/93973142-57012700-fd91-11ea-8de6-94eb629231a7.png)

2. 
![image](https://user-images.githubusercontent.com/58077446/93973168-5ff1f880-fd91-11ea-9341-2bb14a091dac.png)

3. 
![image](https://user-images.githubusercontent.com/58077446/93973189-67190680-fd91-11ea-9a1c-0d5dbf458fe4.png)

4.
![image](https://user-images.githubusercontent.com/58077446/93973202-6d0ee780-fd91-11ea-9a22-efd7b3fe181d.png)

5. openstack loadbalancer set lb3 --description lblb3
![image](https://user-images.githubusercontent.com/58077446/93973273-8adc4c80-fd91-11ea-92ff-50348f320643.png)

6. openstack loadbalancer set lb2 --description test
![image](https://user-images.githubusercontent.com/58077446/93973306-9d568600-fd91-11ea-9bc9-e357fb12bfa1.png)

7.  openstack loadbalancer set lb2 --description ""
![image](https://user-images.githubusercontent.com/58077446/93973776-67fe6800-fd92-11ea-8cbe-2298a9651d5e.png)

2020-09-23 11:21 UTC, OmkarTelee-A10 approved these changes

2020-09-23 16:05 UTC, AfrinChakure-GSLab requested changes

2020-09-23 16:05 UTC, AfrinChakure-GSLab commented on a10_octavia/controller/worker/tasks/virtual_server_tasks.py
> +        description = str(loadbalancer.description) if loadbalancer.description else ""
```
description = loadbalancer.description
if not loadbalancer.description:
    description = None
else:
    description =  loadbalancer.description.strip()

```

2020-09-24 04:20 UTC, NehaKembalkarA10 commented on a10_octavia/controller/worker/tasks/virtual_server_tasks.py
> +        description = str(loadbalancer.description) if loadbalancer.description else ""
yes it works.

2020-09-24 04:45 UTC, afrin-chakure-a10 submitted a review, later dismissed

2020-09-24 05:06 UTC, hthompson-a10 approved these changes

2020-09-24 05:06 UTC, OmkarTelee-A10 approved these changes

2020-09-24 05:08 UTC, merged