[BUG][STACK-1669]: Fixed an issue for creating another LB on a different project under same parent partition
a10networks/a10-octavia pull request #208
Opened 2020-10-14 13:57 UTC by NehaKembalkarA10

## Description
- Severity Level: Medium
- Allowing to create another(second) load balancer of a different project(child2_project) under same partition(parent partition) when there is already a load balancer with different project(child1_project) under same partition(parent partition) exists.

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-1669

## Technical Approach
- Shifted hmt logic from task `CreateRackVthunderEntry` to task  `CheckExistingProjectToThunderMappedEntries` ensuring correct partition_name is stored for vthunder_config.
- Returning the correct `vthunder_config` from `CheckExistingProjectToThunderMappedEntries` and using it in further tasks(`CheckExistingThunderToProjectMappedEntries` and `CreateRackVthunderEntry`) by modifying the flows `get_create_rack_vthunder_load_balancer_flow` and `get_rack_vthunder_for_lb_subflow`

## Test Cases
Test cases resolved by the above changes:
lb1 --->  project_id: child1,  partition: parent
lb2 --->  project_id: child2,  partition: parent -----> OK
lb3 --->  project_id: child2,  partition: parent -----> OK

lb1 --->  project_id: child1,   partition: parent
lb2 --->  project_id: child1,  partition: parent  ---> OK

## Manual Testing
By performing the steps mentioned in the bug https://a10networks.atlassian.net/browse/STACK-1669, getting following results:
loadbalancer lc1 is getting created under parent partition
**loadbalancer lcc1 is getting created under parent partition
loadbalancer lcc2 is getting created under parent partition**

2020-10-15 08:07 UTC, afrin-chakure-a10 requested changes

2020-10-15 09:48 UTC, NehaKembalkarA10 commented on a10_octavia/controller/worker/tasks/a10_database_tasks.py
> +        if ((hierarchical_mt == 'enable') and (CONF.a10_global.use_parent_partition)):
Done

2020-10-19 07:19 UTC, OmkarTelee-A10 approved these changes

2020-10-19 07:29 UTC, afrin-chakure-a10 approved these changes

2020-10-19 07:30 UTC, merged