[BUG][STACK-1754] [l7poicy_listener]: creating l7policy for vport:http/http will change vport's name
a10networks/a10-octavia pull request #307
Opened 2021-01-22 12:23 UTC by rahulkatre-a10

## Description
Severity level: high
Description: When l7policy is created, the vport name will be changed to listener's name replacing listener's ID used as name.

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-1754

## Technical Approach
- Changed the name to ID for axapi requests.

## Manual Testing
- Created l7 policy for listener and observed listener's name.
- Deleted the same l7 policy.

Note: After doing these changes, unable to delete l7 policy giving an error "ACOSException: 17039364 This aFleX is in use", fixed this issue by replacing the update to replace the call.

2021-01-25 02:54 UTC, ytsai-a10 requested changes
I saw l7rule_tasks.py has similar problem, can you help also fix them?

2021-01-27 06:35 UTC, rahulkatre-a10 commented
> I saw l7rule_tasks.py has similar problem, can you help also fix them?

change added

2021-01-27 12:21 UTC, ytsai-a10 approved these changes

2021-01-27 12:41 UTC, afrin-chakure-a10 approved these changes

2021-01-27 12:42 UTC, NehaKembalkarA10 approved these changes

2021-01-27 13:07 UTC, merged