[BUG][STACK-2230]: [vthunder_dataport] dataport was not deleted when deleting pool directly
a10networks/a10-octavia pull request #360
Opened 2021-04-12 14:33 UTC by rahulkatre-a10

## Description
Severity Level: High
Issue Description: data port was not deleted when deleting pool directly.
by deleting member to delete dataport is fine.

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-2230

## Technical Approach
- Added interface deletion flow for pool deletion

## Manual Testing
- Create pool
  openstack loadbalancer pool list
+--------------------------------------+--------+----------------------------------+---------------------+----------+--------------+----------------+
| id                                   | name   | project_id                       | provisioning_status | protocol | lb_algorithm | admin_state_up |
+--------------------------------------+--------+----------------------------------+---------------------+----------+--------------+----------------+
| 57690cb3-8b42-4c6c-82da-0c22cd7bdbc0 | pool-1 | b0f382575e8e4c7eb8e3044553500f15 | ACTIVE              | HTTP     | ROUND_ROBIN  | True           |
+--------------------------------------+--------+----------------------------------+---------------------+----------+--------------+----------

- Created 2 members in 2 different subnet. 
   stack@rahul:~/rahul/a10-octavia$ openstack loadbalancer member list pool-1
+--------------------------------------+----------+----------------------------------+---------------------+----------------+---------------+------------------+--------+
| id                                   | name     | project_id                       | provisioning_status | address        | protocol_port | operating_status | weight |
+--------------------------------------+----------+----------------------------------+---------------------+----------------+---------------+------------------+--------+
| 01c6a36f-fa29-4ae8-b7da-8e18d782a223 |          | b0f382575e8e4c7eb8e3044553500f15 | ACTIVE              | 192.168.13.90  |            80 | NO_MONITOR       |      1 |
| adb024ac-8af4-462f-a4e3-5fb401e15562 | member-1 | b0f382575e8e4c7eb8e3044553500f15 | ACTIVE              | 192.168.12.121 |            80 | NO_MONITOR       |      1 |
+--------------------------------------+----------+----------------------------------+---------------------+----------------+---------------+------------------+--------+

- Check vthunder
vThunder(NOLICENSE)#show interface brief
Port                Link  Dupl  Speed  Trunk Vlan Encap     MAC             IP Address          IPs Flags  Name
---------------------------------------------------------------------------------------------------------------
mgmt                Up    auto  auto   N/A   N/A  N/A       fa16.3e39.d118  192.168.0.106/24      1
1                   Up    Full  10000  none  1    N/A       fa16.3e81.0510  10.0.11.168/24        1  DataPort
2                   Up    Full  10000  none  1    N/A       fa16.3e6d.6e61  10.0.12.113/24        1  DataPort
3                   Up    Full  10000  none  1    N/A       fa16.3e2f.989b  10.0.13.154/24        1  DataPort
4                   Up    Full  10000  none  1    N/A       fa16.3e27.2b3e  10.0.14.109/24        1  DataPort

- Delete pool
 Check vthunder
 vThunder(NOLICENSE)#show interface brief 
Port                Link  Dupl  Speed  Trunk Vlan Encap     MAC             IP Address          IPs Flags  Name
---------------------------------------------------------------------------------------------------------------
mgmt                Up    auto  auto   N/A   N/A  N/A       fa16.3e39.d118  192.168.0.106/24      1
1                   Up    Full  10000  none  1    N/A       fa16.3e81.0510  10.0.11.168/24        1  DataPort
2                   Up    Full  10000  none  1    N/A       fa16.3e6d.6e61  10.0.12.113/24        1  DataPort

2021-04-12 15:45 UTC, ytsai-a10 commented
- I think your changes is only for vthunder flow but rack flow may be affected. So, I wonder if we can **seperate get_delete_pool_flow to rack flow (e.g. get_delete_pool_rack_flow) and vthunder flow (e.g. get_delete_pool_flow) like other places.**

For example:
at 
https://github.com/a10networks/a10-octavia/blob/42f26c0203a11de4aefa6c30fe93e7760609d8d8/a10_octavia/controller/worker/controller_worker.py#L575
change to
```
if listener.project_id in CONF.hardware_thunder.devices:
    delete_pool_tf = self._taskflow_load(
        self._pool_flows.get_delete_pool_rack_flow(
            members, health_monitor, store), store=store)
else:
    delete_pool_tf = self._taskflow_load(
        self._pool_flows.get_delete_pool_flow(
            members, health_monitor, store), store=store)
```

---

- **Please test this case in rack flow and vthunder flow**

2021-04-13 01:09 UTC, ytsai-a10 requested changes
please help take care both rack and vthunder cases.

2021-04-13 09:42 UTC, ytsai-a10 approved these changes

2021-04-13 09:44 UTC, rahulkatre-a10 commented
> please help take care both rack and vthunder cases.

Added the changes for rack flow, added test results for rack flow

2021-04-13 11:58 UTC, NehaKembalkarA10 approved these changes

2021-04-13 15:04 UTC, merged