[BUG][Stack 2261]: [vthunder mode switch] Return error response when vthunder has loadbalancer with topology
a10networks/a10-octavia pull request #371
Opened 2021-04-21 08:21 UTC by mohdadeebkhan

## Description
Severity Level Medium
Issue Description: [vthunder: mode switch] failed to create lb and get "AttributeError: 'NoneType' object has no attribute 'id' when change from single to active-standby

## Jira Ticket
- https://a10networks.atlassian.net/browse/STACK-2261

## Technical Approach
- Limitation:
1. Don't support for changing topology when loadbalancer already created on vThunder instance.
2. Response error to user when existing vthunder has lb with differnet topology

- Added CheckExistingVthunderTopology task in a10_database_tasks.py file. This task will compare the topology from config file to the topology of existing lb in vthunder. If topology does not match then exception will be raised.

## Test Cases
- Added test_CheckExistingVthunderTopology_execute_raised_exception in test_a10_database_tasks.py file

## Manual Testing
1) Create lbs in active standby topology
```
stack@adeeb:~$ openstack loadbalancer list
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| id                                   | name | project_id                       | vip_address | provisioning_status | provider |
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| a44740f5-75b9-4213-a324-61a6500d484a | lb1  | 5327a262f3dd48f48a3fa4c9c9016894 | 10.0.11.196 | ACTIVE              | a10      |
| 223c7715-f3bd-4fcb-ae1b-818114c97f5c | lb2  | 5327a262f3dd48f48a3fa4c9c9016894 | 10.0.12.114 | ACTIVE              | a10      |
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
```

2) Change the topology to single in config file and create the loadbalancer
```
loadbalancer_topology = SINGLE

openstack loadbalancer create --vip-subnet-id provider-vlan-13-subnet --name lb3

logs:
Apr 21 04:21:46 adeeb a10-octavia-worker[22675]: INFO a10_octavia.controller.queue.endpoint [-] Creating load balancer 'c26dde1f-fe5e-434d-b567-480f2b52bb1b'...
Apr 21 04:21:46 adeeb a10-octavia-worker[22675]: INFO a10_octavia.controller.worker.flows.a10_load_balancer_flows [-] TOPOLOGY ===SINGLE
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR a10_octavia.controller.worker.tasks.a10_database_tasks [-] Other loadbalancer exists in vthunder with: ACTIVE_STANDBY topology
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: WARNING a10_octavia.controller.worker.controller_worker [-] Task 'a10_octavia.controller.worker.tasks.a10_database_tasks.CheckExistingVthunderTopology' (1fc8eacb-09a2-4829-8baf-f1b21b6530cc) transitioned into state 'FAILURE' from state 'RUNNING'
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: 3 predecessors (most recent first):
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]:   Atom 'octavia.controller.worker.tasks.database_tasks.ReloadLoadBalancer' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'loadbalancer_id': u'c26dde1f-fe5e-434d-b567-480f2b52bb1b'}, 'provides': <octavia.common.data_models.LoadBalancer object at 0x7f621f187b50>}
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]:   |__Atom 'octavia.controller.worker.tasks.lifecycle_tasks.LoadBalancerIDToErrorOnRevertTask' {'intention': 'EXECUTE', 'state': 'SUCCESS', 'requires': {'loadbalancer_id': u'c26dde1f-fe5e-434d-b567-480f2b52bb1b'}, 'provides': None}
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]:      |__Flow 'octavia-create-loadbalancer-flow': InvalidTopology: Invalid topology specified: vthunder has other loadbalancer with ACTIVE_STANDBY topology
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR a10_octavia.controller.worker.controller_worker Traceback (most recent call last):
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR a10_octavia.controller.worker.controller_worker   File "/usr/local/lib/python2.7/dist-packages/taskflow/engines/action_engine/executor.py", line 53, in _execute_task
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR a10_octavia.controller.worker.controller_worker     result = task.execute(**arguments)
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR a10_octavia.controller.worker.controller_worker   File "/opt/stack/adeeb/a10-octavia/a10_octavia/controller/worker/tasks/a10_database_tasks.py", line 948, in execute
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR a10_octavia.controller.worker.controller_worker     raise oct_excep.InvalidTopology(topology=msg)
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR a10_octavia.controller.worker.controller_worker InvalidTopology: Invalid topology specified: vthunder has other loadbalancer with ACTIVE_STANDBY topology
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR a10_octavia.controller.worker.controller_worker
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: WARNING a10_octavia.controller.worker.controller_worker [-] Task 'a10_octavia.controller.worker.tasks.a10_database_tasks.CheckExistingVthunderTopology' (1fc8eacb-09a2-4829-8baf-f1b21b6530cc) transitioned into state 'REVERTED' from state 'REVERTING'
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: WARNING a10_octavia.controller.worker.controller_worker [-] Task 'octavia.controller.worker.tasks.database_tasks.ReloadLoadBalancer' (ea5e1b4f-6db8-49e9-ab40-66c74927c51f) transitioned into state 'REVERTED' from state 'REVERTING'
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: WARNING a10_octavia.controller.worker.controller_worker [-] Task 'octavia.controller.worker.tasks.lifecycle_tasks.LoadBalancerIDToErrorOnRevertTask' (05d82107-88c8-45b3-91d6-e3d42d8522e9) transitioned into state 'REVERTED' from state 'REVERTING'
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: WARNING a10_octavia.controller.worker.controller_worker [-] Flow 'octavia-create-loadbalancer-flow' (efee761d-8743-478c-8e4c-a242a440ddac) transitioned into state 'REVERTED' from state 'RUNNING'
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server [-] Exception during message handling: InvalidTopology: Invalid topology specified: vthunder has other loadbalancer with ACTIVE_STANDBY topology
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server Traceback (most recent call last):
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/server.py", line 166, in _process_incoming
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 265, in dispatch
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 194, in _do_dispatch
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server   File "/opt/stack/adeeb/a10-octavia/a10_octavia/controller/queue/endpoint.py", line 45, in create_load_balancer
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server     self.worker.create_load_balancer(load_balancer_id, flavor)
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tenacity/__init__.py", line 292, in wrapped_f
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server     return self.call(f, *args, **kw)
Apr 21 04:21:47 adeeb a10-octavia-worker[22675]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tenacity/__init__.py", line 358, in call
Apr 21 04:21:4 [...]

2021-04-23 00:18 UTC, hthompson-a10 requested changes
Does this work when just creating a loadbalancer on a new vThunder?

loadbalancer single topology == "SINGLE"
vthunder single topology == "STANDALONE"

2021-04-23 04:54 UTC, mohdadeebkhan commented
> Does this work when just creating a loadbalancer on a new vThunder?
> 
> loadbalancer single topology == "SINGLE"
> vthunder single topology == "STANDALONE"

As discussed over teams, Added comment in the task that this task is only meant to use with vthunder flows

2021-04-26 07:24 UTC, ytsai-a10 approved these changes

2021-04-26 08:30 UTC, NehaKembalkarA10 approved these changes

2021-04-27 00:56 UTC, merged