[a10-octavia v1.3][STACK-2330] device-name flaovr support
a10networks/a10-octavia pull request #394
Opened 2021-05-11 09:57 UTC by ytsai-a10

## Description
document for the feature: https://teams.microsoft.com/l/file/45BFD3D5-6406-4A7F-B2C6-EACF24CA9E31?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v1.3%20-%20Device%20Flavor%2FDevice%20Flavor.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-2330

## Technical Approach
document for the feature: https://teams.microsoft.com/l/file/45BFD3D5-6406-4A7F-B2C6-EACF24CA9E31?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v1.3%20-%20Device%20Flavor%2FDevice%20Flavor.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb

## Config Changes

<pre>
<b>[hardware_thunder]
devices = [
                    {
                     "project_id": "3d21c71c4e4040599933bda62a76ae2f",
                     "ip_address": "192.168.90.46",
                     "username": "admin",
                     "password": "a10",
                     "device_name": "admin"
                     },
                    {
                     "project_id": "9955a18b75fa4c30bb865d72b5a86a6a",
                     "ip_address": "192.168.90.46",
                     "username": "admin",
                     "password": "a10",
                     "partition_name": "p7",
                     "device_name": "child1",
                     "hierarchical_multitenancy": "enable"
                     },
                    {
                     "project_id": "b612261c15374f1a896f4c3830042f48",
                     "ip_address": "192.168.90.46",
                     "username": "admin",
                     "password": "a10",
                     "partition_name": "p7",
                     "device_name": "child2",
                     "hierarchical_multitenancy": "enable",
                     },
                    {
                     "ip_address": "192.168.90.46",
                     "username": "admin",
                     "password": "a10",
                     "partition_name": "p7",
                     "device_name": "dev1"
                     },
                    {
                     "ip_address": "192.168.90.45",
                     "username": "admin",
                     "password": "a10",
                     "device_name": "dev2"
                     },
                    {
                     "ip_address": "192.168.90.46",
                     "username": "admin",
                     "password": "a10",
                     "device_name": "dev3",
                     "hierarchical_multitenancy": "enable"
                     },
             ]
</b>
</pre>

## Test Cases
- flavor schema 
```shell
openstack loadbalancer provider capability list a10
```

---------------------

 - use device-name flavor
Flavor:
```json
{ 
	"device-name": "dev2"
}
```

```shell
openstack loadbalancer flavorprofile create --name fp_dev2 --provider a10 --flavor-data '{"device-name": "dev2"}'
openstack loadbalancer flavor create --name f_dev2 --flavorprofile fp_dev2 --description "use device dev2" --enable
openstack loadbalancer create --flavor f_dev2 --vip-subnet-id tp91 --vip-address 192.168.91.56 --name vip1
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name vport1 vip1
```

---------------------

 - partition support
```
{ 
	"device-name": "dev1"
}
```

```shell
openstack loadbalancer flavorprofile create --name fp_dev1 --provider a10 --flavor-data '{"device-name": "dev1"}'
openstack loadbalancer flavor create --name f_dev1 --flavorprofile fp_dev1 --description "use device dev1" --enable

openstack loadbalancer create --flavor f_dev1 --vip-subnet-id tp91 --vip-address 192.168.91.56 --name vip1
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name vport1 vip1
```

---------------------

 - HMT
```
{ 
	"device-name": "dev3"
}
```

```
openstack loadbalancer flavorprofile create --name fp_dev3 --provider a10 --flavor-data '{"device-name": "dev3"}'
openstack loadbalancer flavor create --name f_dev3 --flavorprofile fp_dev3 --description "use device dev1" --enable

openstack loadbalancer create --flavor f_dev3 --vip-subnet-id tp91 --vip-address 192.168.91.56 --project child1 --name vip1
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name vport1 vip1
```

---------------------

- use parent partition

```
[a10_global]
use_parent_partition=True
```

```
openstack loadbalancer create --flavor f_dev3 --vip-subnet-id tp91 --vip-address 192.168.91.56 --project child1 --name vip1
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name vport1 vip1
```

---------------------

## Manual Testing
- flavor schema 
```shell
stack@ytsai-openstack:~/source/a10-octavia/device-flavor$ openstack loadbalancer provider capability list a10
+---------------------------------+----------------------------------------------------------------------------------------------------+
| name                            | description                                                                                        |
+---------------------------------+----------------------------------------------------------------------------------------------------+
| server.name-expressions         | Specify name expression to match members and axapi that will apply to the server                   |
| nat-pool-list                   | Specify axapi of nat pools for loadbalancer                                                        |
| health-monitor.name-expressions | Specify name expression to match healthmonitor and axapi that will apply to the health monitor     |
| device-name                     | Specify vthunder device name that used for this loadbalancer                                       |
| virtual-server.name-expressions | Specify name expression to match loadbalancers and axapi that will apply to the slb virtual-server |
| nat-pool                        | Specify axapi of default nat pool for loadbalancer                                                 |
| virtual-port.name-expressions   | Specify name expression to match listeners and axapi that will apply to the vport                  |
| service-group.name-expressions  | Specify name expression to match pools and axapi that will apply to the service-group              |
| server                          | Specify axapi that will apply to the server                                                        |
| service-group                   | Specify axapi that will apply to the service-group                                                 |
| virtual-port                    | Specify axapi that will apply to the vport                                                         |
| virtual-server                  | Specify axapi that will apply to the slb virtual-server                                            |
| health-monitor                  | Specify axapi that will apply to the health monitor                                                |
+---------------------------------+----------------------------------------------------------------------------------------------------+
```
---------------

 - use device-name flavor
```
stack@ytsai-openstack:~/source/a10-octavia/device-flavor$ openstack loadbalancer create --flavor f_dev2 --vip-subnet-id tp91 --vip-address 192.168.91.56 --name vip1
+---------------------+--------------------------------------+
| Field               | Value                   [...]

2021-05-12 22:05 UTC, hthompson-a10 requested changes

2021-05-12 22:05 UTC, hthompson-a10 commented on a10_octavia/common/utils.py
> +        vthunder_conf.device_name_as_key = True
Maybe indentation is weird on github.  Looks like we are always setting `device_name_as_key` as true. Which means the check duplicate logic for HMT is never called.

2021-05-12 22:05 UTC, hthompson-a10 commented on a10_octavia/common/utils.py
> +        vthunder_conf.device_name_as_key = True
To follow onto this, we don't know that they want to use the device name for creation until they actively use the flavor.

2021-05-13 03:49 UTC, hthompson-a10 commented on a10_octavia/common/utils.py
> +        vthunder_conf.device_name_as_key = True
Missed the iteration during review. nvm

2021-05-13 06:19 UTC, ytsai-a10 commented on a10_octavia/common/exceptions.py
> +        super(NoFreeSetId, self).__init__(msg=msg)
fixed

2021-05-13 06:23 UTC, ytsai-a10 commented on a10_octavia/controller/worker/tasks/vthunder_tasks.py
> +                    raise exceptions.FlavorDevieNotFound(device_flavor)
fixed

2021-05-13 06:55 UTC, ytsai-a10 commented on a10_octavia/controller/worker/tasks/vthunder_tasks.py
> +    def execute(self, loadbalancer, vthunder_config, device_config_dict, flavor_data=None):
added

2021-05-13 20:40 UTC, hthompson-a10 approved these changes

2021-05-17 06:20 UTC, NehaKembalkarA10 approved these changes

2021-06-02 12:51 UTC, merged