[STACK-2374] configuration sync overwrite a10-octavia config
a10networks/a10-octavia pull request #418
Opened 2021-05-27 10:17 UTC by ytsai-a10

## Description
- Required: Severity Level High
- Required: Issue Description
Configuration sync. overwrite a10-octavia configuration. In our code we sleep 30 seconds to wait configuration sync., but in slow or busy machine the configuration sync may take longer. And if a10-octavia configure vThunder before configuration sync. finished, configuration may lost.

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-2374

## Technical Approach
- Actually we don't need configuration sync. because VCS will do configuration merge during vcs negotiation. So, just remove the configuration sync. tasks and let VCS handle the configuration merge between vMaster and vBlade.
- And the only thing need to sync. is the slb server for a10-octavia health manager. i.e.:
```
health monitor octavia_health_monitor
  retry 5
  override-ipv4 10.64.3.103
  override-port 5550
  interval 5 timeout 3
  method udp port 5550
  exit-module
!
slb server octavia_health_manager_controller 10.64.3.103
  health-check octavia_health_monitor
  exit-module
!
```
we just need to make sure VCS can merge this configuration correctly.

## Config Changes
<pre>
<b>N/A</b>
</pre>

## Test Cases
- create LB in server103 demo project
```
openstack loadbalancer create --name v21 --vip-subnet-id private-11-subnet --project demo
```

## Manual Testing
 - openstack log:
```
stack@qa-103:~/a10-octavia$ openstack loadbalancer create --name v21 --vip-subnet-id private-11-subnet --project demo
+---------------------+--------------------------------------+
| Field               | Value                                |
+---------------------+--------------------------------------+
| admin_state_up      | True                                 |
| created_at          | 2021-05-27T09:31:48                  |
| description         |                                      |
| flavor_id           | None                                 |
| id                  | e16d0d2e-ab99-4848-a5ac-b7b62296c427 |
| listeners           |                                      |
| name                | v21                                  |
| operating_status    | OFFLINE                              |
| pools               |                                      |
| project_id          | 13c0071f44a34eebb0665d19bd55477d     |
| provider            | a10                                  |
| provisioning_status | PENDING_CREATE                       |
| updated_at          | None                                 |
| vip_address         | 10.0.11.101                          |
| vip_network_id      | 9952482a-2a3a-4bee-9124-4d1cb57227f5 |
| vip_port_id         | c870d7e5-2cf3-4bff-a490-c6dfa42e65ff |
| vip_qos_policy_id   | None                                 |
| vip_subnet_id       | c882ac6f-42f5-4161-a8f0-b9cda339c740 |
+---------------------+--------------------------------------+
stack@qa-103:~/a10-octavia$ openstack loadbalancer list
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| id                                   | name | project_id                       | vip_address | provisioning_status | provider |
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| ded9c0e5-f225-43f7-8743-ec2b3ef78f5b | v1   | 3847395f58824532aacfc866a109f043 | 10.0.11.231 | ACTIVE              | a10      |
| e16d0d2e-ab99-4848-a5ac-b7b62296c427 | v21  | 13c0071f44a34eebb0665d19bd55477d | 10.0.11.101 | ACTIVE              | a10      |
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
```

- vThunder log:
```
vThunder-vBlade[2/2](NOLICENSE)#show running-config
!Current configuration: 670 bytes
!Configuration last updated at 10:50:31 IST Thu May 27 2021
!Configuration last saved at 10:50:31 IST Thu May 27 2021
!64-bit Advanced Core OS (ACOS) version 5.2.1-p1, build 56 (Feb-16-2021,19:16)
!
vrrp-a common
  device-id 2
  set-id 2
  enable
!
device-context 1
  vcs enable
!
device-context 2
  vcs enable
!
vcs floating-ip 192.168.0.100 255.255.255.0
vcs failure-retry-count forever
!
vcs device 1
  priority 200
  interfaces management
  enable
!
vcs device 2
  priority 100
  interfaces management
  enable
!
!
device-context 1
  interface management
    ip address dhcp
!
device-context 2
  interface management
    ip address dhcp
!
interface ethernet 1/1
  name DataPort
  enable
  ip address dhcp
!
interface ethernet 1/2
  name DataPort
  enable
  ip address dhcp
!
interface ethernet 1/3
  name DataPort
  enable
  ip address dhcp
!
interface ethernet 2/1
  name DataPort
  enable
  ip address dhcp
!
interface ethernet 2/2
  name DataPort
  enable
  ip address dhcp
!
interface ethernet 2/3
  name DataPort
  enable
  ip address dhcp
!
!
vrrp-a vrid 1
  device-context 1
    blade-parameters
      priority 150
!
health monitor octavia_health_monitor
  retry 5
  override-ipv4 10.64.3.103
  override-port 5550
  interval 5 timeout 3
  method udp port 5550
!
slb server octavia_health_manager_controller 10.64.3.103
  health-check octavia_health_monitor
!
slb virtual-server e16d0d2e-ab99-4848-a5ac-b7b62296c427 10.0.11.101
!
!
cloud-services meta-data
  enable
  provider openstack
!
end
!Current config commit point for partition 0 is 0 & config mode is classical-mode
```

2021-06-02 00:25 UTC, hthompson-a10 approved these changes

2021-06-03 05:15 UTC, sana-a10 requested changes
If we don't need ConfigureVRRPSync anywhere we can remove the task as well.
https://github.com/a10networks/a10-octavia/pull/418/files#diff-6260002460a7dd265fa6c520a377d1e7a97a26347b54b598c482098955dd9e52L384
 
Also we should remove the constants (CONFIGURE_VRRP_SYNC, WAIT_FOR_MASTER_SYNC) as well if we are not going to use it anywhere.

2021-06-03 05:44 UTC, sana-a10 approved these changes

2021-06-03 05:52 UTC, NehaKembalkarA10 approved these changes

2021-06-03 06:13 UTC, merged