[BUG][STACK-2378]: [vthunder] LB is in PENDING_DELETE for 30+ minutes even when the amp_busy_wait_sec=100
a10networks/a10-octavia pull request #423
Opened 2021-06-01 11:19 UTC by NehaKembalkarA10

## Description
- Severity Level: High
- Issue Description: When a loadbalancer goes into ERROR state while its creation and then if we try to delete it, then the loadbalancer remains in PENDING_DELETE state for a long time instead of simply deleting it.

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-2378

## Technical Approach
- As vthunder will be None in the case where LB goes into ERROR state, so returning None from GetMasterVThunder task if vthunder is None at GetMasterVThunder task else returning the master vthunder.
- If vthunder is None, then returning from VCSSyncWait task without executing it further.

## Manual Testing
1. Create a loadbalancer and wait till it is ACTIVE and vThunder is ready

stack@neha:~$ openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name lb1
```
+---------------------+--------------------------------------+
| Field               | Value                                |
+---------------------+--------------------------------------+
| admin_state_up      | True                                 |
| created_at          | 2021-06-01T06:22:20                  |
| description         |                                      |
| flavor_id           | None                                 |
| id                  | d7a73f44-c5cf-4625-bd30-89d34b1300bf |
| listeners           |                                      |
| name                | lb1                                  |
| operating_status    | OFFLINE                              |
| pools               |                                      |
| project_id          | 60b9bb1eeddb4bfc8ab3da24e7c4eee5     |
| provider            | a10                                  |
| provisioning_status | PENDING_CREATE                       |
| updated_at          | None                                 |
| vip_address         | 10.0.11.111                          |
| vip_network_id      | 594c81c0-015f-4cc5-97fd-a1226e443d8b |
| vip_port_id         | 3e964c31-6656-4219-8362-0e51756a5ed8 |
| vip_qos_policy_id   | None                                 |
| vip_subnet_id       | 5841d92a-8f9d-4c8a-8aed-ebd186899a13 |
+---------------------+--------------------------------------+
```

stack@neha:~$ openstack loadbalancer list
```
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| id                                   | name | project_id                       | vip_address | provisioning_status | provider |
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| d7a73f44-c5cf-4625-bd30-89d34b1300bf | lb1  | 60b9bb1eeddb4bfc8ab3da24e7c4eee5 | 10.0.11.111 | ACTIVE              | a10      |
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
```

2.  openstack loadbalancer flavorprofile create --name fp_natpool_1 --provider a10 --flavor-data '{"nat-pool":{"pool-name":"test","start-address":"1.1.1.2","end-address":"1.1.1.10","netmask":"/24"}}'

3. openstack loadbalancer flavor create --name f_natpool_1 --flavorprofile fp_natpool_1

4. Create a loadbalancer with flavor f_natpool_1

stack@neha:~$ openstack loadbalancer create --name vf1 --vip-subnet-id provider-vlan-11-subnet --flavor f_natpool_1
```
+---------------------+--------------------------------------+
| Field               | Value                                |
+---------------------+--------------------------------------+
| admin_state_up      | True                                 |
| created_at          | 2021-06-01T07:06:11                  |
| description         |                                      |
| flavor_id           | 93495cb9-5de3-44f8-8314-0034ec58c828 |
| id                  | b0f3aa9e-ca43-4759-b3f5-b246617c4d02 |
| listeners           |                                      |
| name                | vf1                                  |
| operating_status    | OFFLINE                              |
| pools               |                                      |
| project_id          | 60b9bb1eeddb4bfc8ab3da24e7c4eee5     |
| provider            | a10                                  |
| provisioning_status | PENDING_CREATE                       |
| updated_at          | None                                 |
| vip_address         | 10.0.11.145                          |
| vip_network_id      | 594c81c0-015f-4cc5-97fd-a1226e443d8b |
| vip_port_id         | 52da6aeb-5389-4308-8376-2aa43d7f91f4 |
| vip_qos_policy_id   | None                                 |
| vip_subnet_id       | 5841d92a-8f9d-4c8a-8aed-ebd186899a13 |
+---------------------+--------------------------------------+
```
stack@neha:~$ openstack loadbalancer list
```
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| id                                   | name | project_id                       | vip_address | provisioning_status | provider |
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| d7a73f44-c5cf-4625-bd30-89d34b1300bf | lb1  | 60b9bb1eeddb4bfc8ab3da24e7c4eee5 | 10.0.11.111 | ACTIVE              | a10      |
| b0f3aa9e-ca43-4759-b3f5-b246617c4d02 | vf1  | 60b9bb1eeddb4bfc8ab3da24e7c4eee5 | 10.0.11.145 | ACTIVE              | a10      |
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
```

5. stack@neha:~$ openstack loadbalancer listener create --name lf1 vf1 --protocol tcp --protocol-port 80
```
+-----------------------------+--------------------------------------+
| Field                       | Value                                |
+-----------------------------+--------------------------------------+
| admin_state_up              | True                                 |
| connection_limit            | -1                                   |
| created_at                  | 2021-06-01T07:07:50                  |
| default_pool_id             | None                                 |
| default_tls_container_ref   | None                                 |
| description                 |                                      |
| id                          | bc92dd0a-c0cf-44d2-be1c-4996d5fb3800 |
| insert_headers              | None                                 |
| l7policies                  |                                      |
| loadbalancers               | b0f3aa9e-ca43-4759-b3f5-b246617c4d02 |
| name                        | lf1                                  |
| operating_status            | OFFLINE                              |
| project_id                  | 60b9bb1eeddb4bfc8ab3da24e7c4eee5     |
| protocol                    | TCP                                  |
| protocol_port               | 80                                   |
| provisioning_status         | PENDING_CREATE                       |
| sni_container_refs          | []                                   |
| timeout_client_data         | 50000                                |
| timeout_member_connect      | 5000                                 |
| timeout_member_data         | 50000                                |
| timeout_tcp_inspect         | 0                                    |
| updated_at                  | None                                 |
| client_ca_tls_container_ref | None                                 |
| client_authentication       | NONE                                 |
| client_crl_container_ref    | None                                 |
+-----------------------------+--------------------------------------+
```

6. stack@neha:~$ openstack loadbalancer pool create --name pf1 --protocol tcp --lb-algorithm LEAST_CONNECTIONS --listener lf1
```
+----------------------+--------------------------------------+
| Field                | Value    [...]

2021-06-01 12:30 UTC, ytsai-a10 submitted a review, later dismissed

2021-06-01 12:52 UTC, rahulkatre-a10 approved these changes

2021-06-02 10:41 UTC, sana-a10 requested changes
I think we should add validation for closing axapi session as well 
so that if the vthunder is none, It should skip closing session 

https://github.com/a10networks/a10-octavia/blob/master/a10_octavia/controller/worker/tasks/decorators.py#L53

2021-06-02 11:00 UTC, NehaKembalkarA10 commented
> I think we should add validation for closing axapi session as well
> so that if the vthunder is none, It should skip closing session
> 
> https://github.com/a10networks/a10-octavia/blob/master/a10_octavia/controller/worker/tasks/decorators.py#L53

Done

2021-06-02 11:08 UTC, sana-a10 approved these changes

2021-06-02 11:53 UTC, ytsai-a10 approved these changes

2021-06-02 11:53 UTC, merged