[Feature][STACK-2764]: Global flavor ID configuration option support
a10networks/a10-octavia pull request #501
Opened 2021-08-30 11:16 UTC by NehaKembalkarA10

## Description
Added support for **default_flavor_id** config option so that users working with a limited feature set don't have to specify as much information during loadbalancer create.

## Design Document
https://teams.microsoft.com/l/file/18D8570C-E48A-4177-A841-7F1F19168BD3?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v1.3.2%20Default%20Flavor-ID%20Support%2FDefault%20flavor-ID%20configuration%20option%20support.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-2764
https://a10networks.atlassian.net/browse/STACK-2795
https://a10networks.atlassian.net/browse/STACK-2796
https://a10networks.atlassian.net/browse/STACK-2816
https://a10networks.atlassian.net/browse/STACK-2818

## Technical Approach
- Added a config option `default_flavor_id` in `a10_global` section of a10-octavia.conf file.
- In `GetFlavorData()` task, assigning default_flavor_id to flavor_id iff a flavor with --flavor parameter is not passed during the loadbalancer creation.
- If flavor with the default_flavor_id is not present in flavor table of octavia DB, then raising an exception **FlavorNotFound**.
- Created FlavorNotFound exception which will give a message as " **Flavor <flavor_id> specified in the configuration file is unable to locate, Please create the flavor in advance**."
- In `create_load_balancer()` method of controller_worker.py, if lb.flavor_id is None and CONF.a10_global.default_flavor_id exists, then making entry of the CONF.a10_global.default_flavor_id into flavor_id column of load_balancer table via `UpdateLoadbalancerInDB()` task.

## Config Changes
Added a new option default_flavor_id in a10_global section

```
[a10_global]
default_flavor_id = <flavor_id>
```

## Test Cases
- Given a default_flavor_id in config file, when flavor with --flavor is not passed while loadbalancer creation, then the flavor with default_flavor_id should be attached to the loadbalancer.
- Given a default_flavor_id in config file, when flavor with --flavor is passed while loadbalancer creation, then the flavor passed with --flavor parameter should be attached to the loadbalancer.
- Given a default_flavor_id in config file, when flavor with --flavor-id is not passed while loadbalancer creation and the flavor does not exist in flavor table, then FlavorNotFount exception should be raised.

## Manual Testing
1. Create a flavorprofile and flavor for virtual-server.

stack@neha-victoria:~#**openstack loadbalancer flavorprofile create --name fp1 --provider a10 --flavor-data '{"virtual-server": {"vport-disable-action":"drop-packet"}}'**

```
+---------------+------------------------------------------------------------+
| Field         | Value                                                      |
+---------------+------------------------------------------------------------+
| id            | 19dd372f-ea9e-4504-96fc-0bd797404687                       |
| name          | fp1                                                        |
| provider_name | a10                                                        |
| flavor_data   | {"virtual-server": {"vport-disable-action":"drop-packet"}} |
+---------------+------------------------------------------------------------+
```
stack@neha-victoria:~#**openstack loadbalancer flavor create --name f1 --flavorprofile fp1 --description "vtest" --enable**
```
+-------------------+--------------------------------------+
| Field             | Value                                |
+-------------------+--------------------------------------+
| id                | 8c5eef93-cc1d-446f-923c-ae4e351b2bc7 |
| name              | f1                                   |
| flavor_profile_id | 19dd372f-ea9e-4504-96fc-0bd797404687 |
| enabled           | True                                 |
| description       | vtest                                |
+-------------------+--------------------------------------+
```

2. Configure the flavor-id to default_flavor_id option in a10-octavia.conf file and restart a10-controller-worker.service
```
[a10_global]
network_type = 'flat'
vrid_floating_ip = "dhcp"
default_flavor_id = "8c5eef93-cc1d-446f-923c-ae4e351b2bc7"
```

3. Create a loadbalancer

stack@neha-victoria:~#**openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name lb1**
```
+---------------------+--------------------------------------+
| Field               | Value                                |
+---------------------+--------------------------------------+
| admin_state_up      | True                                 |
| availability_zone   | None                                 |
| created_at          | 2021-08-30T06:21:04                  |
| description         |                                      |
| flavor_id           | None                                 |
| id                  | 9fb2e875-4bc9-4c09-a7c7-d7828e73cd92 |
| listeners           |                                      |
| name                | lb1                                  |
| operating_status    | OFFLINE                              |
| pools               |                                      |
| project_id          | 64474f828b3c483eafe2be7f5025df0d     |
| provider            | a10                                  |
| provisioning_status | PENDING_CREATE                       |
| updated_at          | None                                 |
| vip_address         | 10.0.11.175                          |
| vip_network_id      | dfe0ea7a-5463-4332-827a-cbf91c86d740 |
| vip_port_id         | a81c2aca-4110-468e-a036-f856f7316299 |
| vip_qos_policy_id   | None                                 |
| vip_subnet_id       | 452aef15-7144-4c2f-87dc-c97dbce2dd3f |
+---------------------+--------------------------------------+
```

stack@neha-victoria:~#openstack loadbalancer list
```
+--------------------------------------+------+----------------------------------+-------------+---------------------+------------------+----------+
| id                                   | name | project_id                       | vip_address | provisioning_status | operating_status | provider |
+--------------------------------------+------+----------------------------------+-------------+---------------------+------------------+----------+
| 9fb2e875-4bc9-4c09-a7c7-d7828e73cd92 | lb1  | 64474f828b3c483eafe2be7f5025df0d | 10.0.11.175 | ACTIVE              | OFFLINE          | a10      |
+--------------------------------------+------+----------------------------------+-------------+---------------------+------------------+----------+
```

mysql> select * from load_balancer;
```
+----------------------------------+--------------------------------------+------+-------------+---------------------+------------------+---------+----------------+-----------------+---------------------+---------------------+----------+--------------------------------------+-------------------+
| project_id                       | id                                   | name | description | provisioning_status | operating_status | enabled | topology       | server_group_id | created_at          | updated_at          | provider | flavor_id                            | availability_zone |
+----------------------------------+--------------------------------------+------+-------------+---------------------+------------------+---------+----------------+-----------------+---------------------+---------------------+----------+--------------------------------------+-------------------+
| 64474f828b3c483eafe2be7f5025df0d | 9fb2e875-4bc9-4c09-a7c7-d7828e73cd92 | lb1  | NULL        | ACTIVE              | OFFLINE          |       1 | ACTIVE_STANDBY | NULL            | 2021-08-3 [...]

2021-08-30 15:45 UTC, ytsai-a10 approved these changes

2021-08-31 02:05 UTC, hthompson-a10 requested changes
Looks good to me. Just some minor nitpicks

2021-08-31 05:12 UTC, NehaKembalkarA10 commented on a10_octavia/common/exceptions.py
> +        msg = ('Flavor {0} specified in the configuration file is unable to locate,'
Done

2021-08-31 05:13 UTC, NehaKembalkarA10 commented on a10_octavia/controller/worker/controller_worker.py
> +        if not lb.flavor_id and CONF.a10_global.default_flavor_id:
Done

2021-08-31 18:26 UTC, hthompson-a10 approved these changes

2021-09-01 01:47 UTC, ytsai-a10 approved these changes

2021-09-01 01:47 UTC, merged